### ISSUE TITLE
GNOME 42

### ISSUE THREAD

**Issue by junocomp** [fffilo/prime-indicator#11]
Please port to GNOME 42

**Comment by matissime** [comment]
I submitted a pr to port the extension to gnome 42, actually to install it you need to build the extension from source by cloning my forked repo https://github.com/matissime/prime-indicator and when you are in the folder, to install it on your system do: 
`make` 
`make install`
after that you need to logout and login again, go to your gnome extensions manager and from here you will be able to enable it:)

**Comment by gigi206** [comment]
+1

**Comment by fffilo** [comment]
Sorry for delay...
