### ISSUE TITLE
Doesn't work for wayland.

### ISSUE THREAD

**Issue by hydroEng** [fffilo/prime-indicator#8]
First of all, great extension, thank you. I have noticed that the indicator does not appear while I am in a wayland session.

Laptop users who want touchpad gestures must use wayland, so that means switching to the intel GPU only in the nvidia config. Then, when playing a game (for example) it is quicker to use this extension (hypothetically) to enable nvidia and log out, and (presumably) log back into the Xorg session.

I am using ubuntu 20.04

**Comment by fffilo** [comment]
Ported to Gnome Shell 40, tested on wayland. Try and reopen if issue still present...
